# Generated by Django 3.2.6 on 2021-08-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed_at',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='text',
        ),
    ]
